name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: echo "No build step required for this app"

      - name: Deploy to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          scp -i $EC2_KEY -r ./* $EC2_USER@$EC2_HOST:/var/www/bookshop
          ssh -i $EC2_KEY $EC2_USER@$EC2_HOST 'pm2 restart app || pm2 start app.js --name "bookshop"'
